#!/usr/bin/env php
<?php
require  dirname($_SERVER['SCRIPT_FILENAME']) . '/config.php';
$file = basename($_SERVER['SCRIPT_FILENAME']);
if (empty($config[$file])) {
	exit(0);
}

$exit = 0;

foreach ($config[$file] as $command) {
	echo "running $command\n";
    $output = array();
    $return = 0;
    exec(__DIR__ . "/$command", $output, $return);
    if ($return) {
		$exit = 1;
        echo implode("\n", $output) . "\n";
        echo "\tFAIL\n";
    } else {
        echo "\tOK\n";
    }
}

exit ($exit);
