#!/bin/sh
# example script running more than one hook.
#
# hooks run from the project root modify existing hooks to only exit on fail.

# Run php code sniffer, always
. .git/hooks/php-cs/pre-commit

# If running on the master branch, run a smoke test
# It's a good habit to use feature branches, therefore committing on the master
# branch should mean some sort of merge/build
grep 'master' .git/HEAD -q && . .git/hooks/smoke-test/pre-commit

# If we made it here, we passed all the hooks. yay! go forth and commit
exit 0
