#!/usr/bin/env php
<?php

require __DIR__ .'/config.php';

if (empty($CONFIG['preCommit'])) {
	exit(0);
}

$exit = 0;

foreach ($CONFIG['preCommit'] as $command) {
    $output = array();
    $return = 0;
    exec(__DIR__ . "/$command", $output, $return);
    if ($return) {
        echo implode("\n", $output) . "\n";
		$exit = 1;
    }
}

exit ($exit);
