#!/usr/bin/env php
<?php

require __DIR__ .'/utils.php';

$stagedFiles = stagedFiles();
$tmpFiles = copyFiles($stagedFiles);

$filename_pattern = '/\.php$/';
$exit_status = 0;

foreach ($tmpFiles as $file) {
    if (!preg_match($filename_pattern, $file)) {
        // don't check files that aren't PHP
        continue;
    }

    $lint_output = array();
    exec("php -l " . escapeshellarg($file), $lint_output, $return);
    if ($return != 0) {
        echo implode("\n", $lint_output), "\n";
        $exit_status = 1;
    }
}

exit($exit_status);
