#!/usr/bin/env php
<?php
require __DIR__ .'/config.php';
require __DIR__ .'/utils.php';

$stagedFiles = stagedFiles();
$tmp = copyFiles($stagedFiles);

$args = $config['phpcs'];
foreach($args as $key => &$value) {
	if ($value === true) {
		$value = "$key";
	} else {
		$value = "$key=$value";
	}
}
$cmd = "phpcs " . implode($args, ' ') . " " . escapeshellarg($tmp['dir']);
exec($cmd, $output, $return);
if ($return != 0) {
	echo $cmd . "\n";
	echo implode("\n", $output), "\n";
	exit(1);
}
